[package]
name = "squire-cli"
description = "Command line front end for Goldbox Squire."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "squire_cli"
path = "src/lib.rs"

[[bin]]
name = "gbs"
path = "src/main.rs"

[dependencies]
squire-core = { path = "../squire-core" }
nix.workspace = true
libc.workspace = true
serde_json.workspace = true
serde.workspace = true
toml.workspace = true
ratatui.workspace = true
crossterm.workspace = true
